spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://8.155.45.227:5432/postgres
    username: postgres
    password: 12345
#    url: jdbc:postgresql://localhost:5432/mybatis
#    username: postgres
#    password: wyx31302
server:
  port: 9090

