spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mybatis
    username: postgres
    password: 1234
server:
  port: 9090
  #wjq到此一游
  #wyx到此一游
